title:              GJ
email:              girishraguvir@gmail.com
description:        Welcome to my website!
author:             Girish Jeyakumar
baseurl:            ""
url:                "https://girishjeyakumar.github.io"

# Social Profiles
twitter_username:   
github_username: "girishjeyakumar"
facebook_username:  
instagram_username: "girishjeyakumar"
linkedin_username: "girish-raguvir-jeyakumar-791019b7"

google_analytics:   UA-176015285-1 

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: compressed
  
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
